Hackathon/Controllers/ElectionController.cs
using Hackathon.Models;
using Hackathon.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Configuration;
using System.Threading.Tasks;
using System.Net.Http;

namespace Hackathon.Controllers
{
   
    public class ElectionController : Controller
    {
        private string WebApiAddress = ConfigurationManager.AppSettings["ApiBaseAddress"];
        private ApplicationDbContext _dbContext = null;

        public ElectionController()
        {
            _dbContext = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _dbContext.Dispose();
        }
        // GET: Election
        public ActionResult Login()
        {
            return View();
        }
        [HttpGet]
        public async Task<ActionResult> ListOfNominees()
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(WebApiAddress);
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                var response = await client.GetAsync("election");
                if (response.IsSuccessStatusCode)
                {
                    var nominees = await response.Content.ReadAsAsync<IList<NomineeForm>>();
                    return View(nominees);
                }
                else
                    return Content("No records");
            }
            
        }
        [HttpPost]
        public ActionResult Login(string flatNo, string password)
        {
            TempData["FlatNo"] = flatNo;
            var loginPerson = _dbContext.BaseDatas.Where(c => c.FlatNumber == flatNo && c.FlatNumber == password).FirstOrDefault(c => c.FlatNumber == flatNo);
            if (loginPerson != null)
            {
                
                return RedirectToAction("Index");
            }
            else
            {
                return View("Login");
            }
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult NomineeRegister()
        {
            var FlatNo = TempData["FlatNo"].ToString();
            TempData["FlatNo"] = FlatNo;
            var NomineeDetails = _dbContext.BaseDatas.Where(c => c.FlatNumber == FlatNo).FirstOrDefault();
            //TempData["CandidateName"] = NomineeDetails.Name;
            if ((DateTime.Now.Year - NomineeDetails.DateOfBirth.Year) >= 21)
            {
                var position = _dbContext.RWAPositions.ToList();
                var ViewModel = new Nominee_Post_ViewModel()
                {
                    Positions = position,
                    Nominees = new NomineeForm()

                };
                return View(ViewModel);
            }
            else
            {
                return View("MinAge");
            }
        }
        [HttpGet]
        public async Task<ActionResult> EditNomineeDetails(int id)
        {
            var position = _dbContext.RWAPositions.ToList();
            var nominee_vm = new Nominee_Post_ViewModel();
            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri(WebApiAddress);
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                var response = await client.GetAsync($"election/{id}");

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    var nominees = await response.Content.ReadAsAsync<NomineeForm>();
                    nominee_vm.Nominees = nominees;
                    nominee_vm.Positions = position;

                    return View("NomineeRegister", nominee_vm);
                }
                return Content("Not going to loop");
            }
            //var nominee = _dbContext.NomineeForms.Include(c => c.RWAPosition).Where(c => c.Id == id).SingleOrDefault();
            //var nominee_vm = new Nominee_Post_ViewModel();
            //nominee_vm.Nominees = nominee;
            //var position = _dbContext.RWAPositions.ToList();
            //nominee_vm.Positions = position;
            //return View("NomineeRegister", nominee_vm);
        }
        [HttpGet]
        public ActionResult DeleteNomineeDetails(int id)
        {
            var nominee = _dbContext.NomineeForms.Include(c => c.RWAPosition).Where(c => c.Id == id).SingleOrDefault();
            var nominee_vm = new Nominee_Post_ViewModel();
            nominee_vm.Nominees = nominee;
            var position = _dbContext.RWAPositions.ToList();
            nominee_vm.Positions = position;
            return View(nominee);
        }
        [HttpPost]
        public async Task<ActionResult> DeleteNomineeDetails(NomineeForm nominee)
        {
            using (var client = new HttpClient())
            {
                
                client.BaseAddress = new Uri(WebApiAddress);
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                var response = await client.DeleteAsync($"election/delete/{nominee.Id}");
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    return Content("Deleted Succesfully");
                }
            }

            return View("MinAge");
        }

        public ActionResult MinAge()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> NomineeRegister(Nominee_Post_ViewModel nomineeForm)
        {
            
            var FlatNo = TempData["FlatNo"].ToString();
            var NomineeDetails = _dbContext.BaseDatas.Where(c => c.FlatNumber == FlatNo).FirstOrDefault();

            if (nomineeForm.Nominees.Qualification == null)
            {
                return Content(" Fill all the details");
            }
            if (nomineeForm.Nominees.Id == 0)
            {
                using (var client = new HttpClient())
                {
                    nomineeForm.Nominees.FlatNumber = TempData["FlatNo"].ToString();
                    client.BaseAddress = new Uri(WebApiAddress);
                    client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                    var response = await client.PostAsJsonAsync("election/new", nomineeForm.Nominees);
                    if(response.StatusCode==System.Net.HttpStatusCode.Created)
                    {
                        return View("DisplayMessage");
                    }
                }
               
            }
            else if(nomineeForm.Nominees.Id!=0)
            {
                using (var client = new HttpClient())
                {
                    nomineeForm.Nominees.FlatNumber = TempData["FlatNo"].ToString();
                    client.BaseAddress = new Uri(WebApiAddress);
                    client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                    var response = await client.PutAsJsonAsync($"election/update/{nomineeForm.Nominees.Id}", nomineeForm.Nominees);
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        return Content("Succesfully edited");
                    }
                }
            }
            return HttpNotFound();

        }
        public ActionResult DisplayMessage()
        {
            return View();
        }
        public async Task<ActionResult> BallotForm()
        {
            var flatNo = TempData["FlatNo"].ToString();
            var voter = _dbContext.VotingDatas.Where(c => c.FlatNo == flatNo).FirstOrDefault();
            if (voter == null)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(WebApiAddress);
                    client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                    var response = await client.GetAsync("election");
                    if (response.IsSuccessStatusCode)
                    {
                        var nominees = await response.Content.ReadAsAsync<List<NomineeForm>>();
                        return View(nominees);
                    }
                    else
                        return Content("No records");
                }
                //var Nominees = _dbContext.NomineeForms.Include(m => m.RWAPosition).ToList();
                //return View(Nominees);
            }
            else
                return Content("Your Vote already Polled");
        }

        public ActionResult Ballot(int id)
        {
            var d = _dbContext.NomineeForms.Where(c => c.Id == id).FirstOrDefault();
            d.Votes++;
            //var voter = new VotingData()
            //{
            //    PresidentId = d.RWAPosition.Id,
            //    FlatNo=d.FlatNumber

            //};
            //_dbContext.VotingDatas.Add(voter);
            _dbContext.SaveChanges();
            return View("Message");
        }
        public ActionResult Message()
        {
            return View();
        }
        public ActionResult Result()
        {
            var winner = _dbContext.NomineeForms.Where(c=>c.RWAPosition.Id==1).OrderByDescending(c => c.Votes);
            int max1 = _dbContext.NomineeForms.Max(p => p.Votes);
            ViewBag.Max = max1;
            return View(winner);
        }
        public ActionResult Result1()
        {
            var winner = _dbContext.NomineeForms.Include(c => c.RWAPosition).ToList();
            int max1 = _dbContext.NomineeForms.Max(p => p.Votes);

Hackathon/Views/Election/BallotForm.cshtml
@model IEnumerable<Hackathon.Models.NomineeForm>

@{
    ViewBag.Title = "BallotForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>BallotForm</h2>



@*@for (int i = 1; i <= 5; i++)
    {*@
@using (Html.BeginForm("BallotForm","Election",FormMethod.Post))
{
    <h2>President Candidates</h2>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CandidateName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Qualification)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrentOccupation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PreviousRwaMember)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublicSectorEmployee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CriminalRecord)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlatNumber)
            </th>
            <th>
                Select Your Candidate
            </th>
        </tr>

        @foreach (var item in Model.Where(j => j.RWAPosition.PositionName == "President"))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CandidateName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Qualification)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentOccupation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PreviousRwaMember)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublicSectorEmployee)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CriminalRecord)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlatNumber)
                </td>
                <td >
                    @*<input type="radio" id="btnPresident" name="btn" value=@item.RWAPosition.Id />*@
                   @* @Html.RadioButton("Select", true, new { id = item.RWAPosition.Id })*@
                    @Html.ActionLink("Vote", "Ballot", "Election", new { id=item.Id},null)
                </td>

            </tr>
        }`
    </table>
    @*<center>
        <input type="submit" value="Vote" id="btnSubmit" class="btn btn-primary"/>
    </center>*@
   
}
@*
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CandidateName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Qualification)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrentOccupation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PreviousRwaMember)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublicSectorEmployee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CriminalRecord)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlatNumber)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Where(j => j.RWAPosition.PositionName == ))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CandidateName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Qualification)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentOccupation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PreviousRwaMember)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublicSectorEmployee)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CriminalRecord)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlatNumber)
                </td>

            </tr>
        }

        </table>*@

Hackathon/Views/Election/DeleteNomineeDetails.cshtml
@model Hackathon.Models.NomineeForm

@{
    ViewBag.Title = "DeleteNomineeDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DeleteNomineeDetails</h2>

<div>
    <h4>NomineeForm</h4>
    <hr />
    @using (Html.BeginForm())
    {
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.RWAPosition.PositionName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RWAPosition.PositionName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Qualification)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Qualification)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CurrentOccupation)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CurrentOccupation)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PreviousRwaMember)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PreviousRwaMember)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PublicSectorEmployee)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PublicSectorEmployee)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CriminalRecord)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CriminalRecord)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FlatNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FlatNumber)
            </dd>



            <dt>
                @Html.DisplayNameFor(model => model.CandidateName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CandidateName)
            </dd>

        </dl>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    </div>
    }
</div>
   

Hackathon/Views/Election/DisplayMessage.cshtml
@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>You are Successfully Registered for Nominations</h2>

Hackathon/Views/Election/Index.cshtml
@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br/><br/><br/>
@using (Html.BeginForm())
{
<center>
    <div>

        To Nominate Urself click here:<button>@Html.ActionLink("Nominee", "NomineeRegister", "Election")</button>
       
    </div>
    <br />
    <div>
        To vote click here:<button>@Html.ActionLink("Voter", "BallotForm", "Election")</button>
    </div>
</center>
}

Hackathon/Views/Election/ListOfNominees.cshtml
@model IEnumerable<Hackathon.Models.NomineeForm>

@{
    ViewBag.Title = "ListOfNominees";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ListOfNominees</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RWAPosition.PositionName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Qualification)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrentOccupation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreviousRwaMember)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PublicSectorEmployee)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CriminalRecord)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FlatNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Votes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CandidateName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RWAPosition.PositionName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Qualification)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrentOccupation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PreviousRwaMember)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PublicSectorEmployee)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CriminalRecord)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FlatNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Votes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CandidateName)
        </td>
        @if (item!= null)
        {
        <td>
            @Html.ActionLink("Edit", "EditNomineeDetails", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "DeleteNomineeDetails", new { id = item.Id })
        </td>
        }
    </tr>
}

</table>

Hackathon/Views/Election/Login.cshtml
@using (Html.BeginForm())

{
    <br/>
    <center>
        <h2>
            <font color="red">
                LogIn To Nominate Or Vote for RWA Elections
            </font>
        </h2>
        <div class="container">
            <div>
                @Html.Label("Flat No")

                @Html.TextBox("FlatNo", "", new { @class = "form-control", autoComplete = "off" })

            </div>

            <br />
            <div>
            </div>
            <br />
            <div>

                @Html.Label("Password")

                @Html.Password("Password", "", new { @class = "form-control", autoComplete = "off" })

            </div>
        </div>
        <br />
        <input type="submit" value="Login" id="btnSubmit" class="btn btn-primary" />

    </center>
}

Hackathon/Views/Election/Message.cshtml
@{
   
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thank You for voting !!!!!</h2>

Hackathon/Views/Election/MinAge.cshtml
@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Your Age is not Eligible For Nominations.Minimum 21 Years are Required</h2>

Hackathon/Views/Election/NomineeRegister.cshtml
@model Hackathon.ViewModel.Nominee_Post_ViewModel

@{
    ViewBag.Title = "NomineeRegister";
}

<h2>Nominee Register</h2>
<h3 style="color:red" >Note: You should be atleast 21 years to nominate</h3>
@using (Html.BeginForm("NomineeRegister","Election",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model=>model.Nominees.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.Nominees.Qualification, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nominees.Qualification, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nominees.Qualification, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nominees.CurrentOccupation, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nominees.CurrentOccupation, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nominees.CurrentOccupation, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nominees.PreviousRwaMember, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.RadioButtonFor(model => model.Nominees.PreviousRwaMember, "True")<span>Yes</span>
                @Html.RadioButtonFor(model => model.Nominees.PreviousRwaMember, "False")<span>No</span>

                @Html.ValidationMessageFor(model => model.Nominees.PreviousRwaMember, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nominees.PublicSectorEmployee, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.RadioButtonFor(model => model.Nominees.PublicSectorEmployee, "True")<span>Yes</span>
                @Html.RadioButtonFor(model => model.Nominees.PublicSectorEmployee, "False")<span>No</span>
                @Html.ValidationMessageFor(model => model.Nominees.PublicSectorEmployee, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nominees.CriminalRecord, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.RadioButtonFor(model => model.Nominees.CriminalRecord, "True")<span>Yes</span>
                @Html.RadioButtonFor(model => model.Nominees.CriminalRecord, "False")<span>No</span>
                @Html.ValidationMessageFor(model => model.Nominees.CriminalRecord, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nominees.RWAPositionId, "RWAPosition", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Nominees.RWAPositionId, new SelectList(Model.Positions, "Id", "PositionName"), "---Select Position--- ", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Nominees.RWAPositionId, "", new { @class = "text-danger" })
        </div>
    </div>
    

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Nominate" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Hackathon/Views/Election/Result.cshtml
@model IEnumerable<Hackathon.Models.NomineeForm>

@{
    ViewBag.Title = "Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Result</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.FlatNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CandidateName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Votes)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.FlatNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CandidateName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Votes)
        </td>


    </tr>
}

</table>